const WORD_SETS = {
    location: [
        [
            { en: 'Beach', ipa: '/biːtʃ/', zh: '海灘', pinyin: 'hǎitān', ja: 'ビーチ', hiragana: 'びーち' },
            { en: 'Mountain', ipa: '/ˈmaʊntɪn/', zh: '山', pinyin: 'shān', ja: '山', hiragana: 'やま' },
            { en: 'Forest', ipa: '/ˈfɒrɪst/', zh: '森林', pinyin: 'sēnlín', ja: '森', hiragana: 'もり' },
            { en: 'Desert', ipa: '/ˈdɛzərt/', zh: '沙漠', pinyin: 'shāmò', ja: '砂漠', hiragana: 'さばく' },
            { en: 'Island', ipa: '/ˈaɪlənd/', zh: '島嶼', pinyin: 'dǎoyǔ', ja: '島', hiragana: 'しま' },
            { en: 'Canyon', ipa: '/ˈkænjən/', zh: '峽谷', pinyin: 'xiágǔ', ja: '渓谷', hiragana: 'けいこく' },
            { en: 'Valley', ipa: '/ˈvæli/', zh: '山谷', pinyin: 'shāngǔ', ja: '谷', hiragana: 'たに' },
            { en: 'Glacier', ipa: '/ˈɡlæsiər/', zh: '冰川', pinyin: 'bīngchuān', ja: '氷河', hiragana: 'ひょうが' },
            { en: 'Swamp', ipa: '/swɒmp/', zh: '沼澤', pinyin: 'zhǎozé', ja: '沼地', hiragana: 'ぬまち' },
            { en: 'Waterfall', ipa: '/ˈwɔːtəfɔːl/', zh: '瀑布', pinyin: 'pùbù', ja: '滝', hiragana: 'たき' },
        ],
        [
            { en: 'Paris', ipa: '/ˈpærɪs/', zh: '巴黎', pinyin: 'bālí', ja: 'パリ', hiragana: 'ぱり' },
            { en: 'Tokyo', ipa: '/ˈtoʊkioʊ/', zh: '東京', pinyin: 'dōngjīng', ja: '東京', hiragana: 'とうきょう' },
            { en: 'London', ipa: '/ˈlʌndən/', zh: '倫敦', pinyin: 'lúndūn', ja: 'ロンドン', hiragana: 'ろんどん' },
            { en: 'Cairo', ipa: '/ˈkaɪroʊ/', zh: '開羅', pinyin: 'kāiluó', ja: 'カイロ', hiragana: 'かいろ' },
            { en: 'Sydney', ipa: '/ˈsɪdni/', zh: '雪梨', pinyin: 'xuělí', ja: 'シドニー', hiragana: 'しどにー' },
            { en: 'Berlin', ipa: '/bɜːrˈlɪn/', zh: '柏林', pinyin: 'bólín', ja: 'ベルリン', hiragana: 'べるりん' },
            { en: 'Rome', ipa: '/roʊm/', zh: '羅馬', pinyin: 'luómǎ', ja: 'ローマ', hiragana: 'ろーま' },
            { en: 'Dubai', ipa: '/duːˈbaɪ/', zh: '杜拜', pinyin: 'dùbài', ja: 'ドバイ', hiragana: 'どばい' },
            { en: 'New York', ipa: '/nuːˈjɔːrk/', zh: '紐約', pinyin: 'niǔyuē', ja: 'ニューヨーク', hiragana: 'にゅーよーく' },
            { en: 'Mumbai', ipa: '/mʊmˈbaɪ/', zh: '孟買', pinyin: 'mèngmǎi', ja: 'ムンバイ', hiragana: 'むんばい' },
        ],
        [
            { en: 'Library', ipa: '/ˈlaɪbrəri/', zh: '圖書館', pinyin: 'túshūguǎn', ja: '図書館', hiragana: 'としょかん' },
            { en: 'Hospital', ipa: '/ˈhɒspɪtl/', zh: '醫院', pinyin: 'yīyuàn', ja: '病院', hiragana: 'びょういん' },
            { en: 'Airport', ipa: '/ˈɛərpɔːrt/', zh: '機場', pinyin: 'jīchǎng', ja: '空港', hiragana: 'くうこう' },
            { en: 'Museum', ipa: '/mjuˈziːəm/', zh: '博物館', pinyin: 'bówùguǎn', ja: '博物館', hiragana: 'はくぶつかん' },
            { en: 'Market', ipa: '/ˈmɑːrkɪt/', zh: '市場', pinyin: 'shìchǎng', ja: '市場', hiragana: 'いちば' },
            { en: 'School', ipa: '/skuːl/', zh: '學校', pinyin: 'xuéxiào', ja: '学校', hiragana: 'がっこう' },
            { en: 'Stadium', ipa: '/ˈsteɪdiəm/', zh: '體育場', pinyin: 'tǐyùchǎng', ja: 'スタジアム', hiragana: 'すたじあむ' },
            { en: 'Theatre', ipa: '/ˈθiːətər/', zh: '劇院', pinyin: 'jùyuàn', ja: '劇場', hiragana: 'げきじょう' },
            { en: 'Temple', ipa: '/ˈtɛmpl/', zh: '廟宇', pinyin: 'miàoyǔ', ja: '神社', hiragana: 'じんじゃ' },
            { en: 'Prison', ipa: '/ˈprɪzən/', zh: '監獄', pinyin: 'jiānyù', ja: '刑務所', hiragana: 'けいむしょ' },
        ],
    ],
    animal: [
        [
            { en: 'Dog', ipa: '/dɒɡ/', zh: '狗', pinyin: 'gǒu', ja: '犬', hiragana: 'いぬ' },
            { en: 'Cat', ipa: '/kæt/', zh: '貓', pinyin: 'māo', ja: '猫', hiragana: 'ねこ' },
            { en: 'Horse', ipa: '/hɔːrs/', zh: '馬', pinyin: 'mǎ', ja: '馬', hiragana: 'うま' },
            { en: 'Rabbit', ipa: '/ˈræbɪt/', zh: '兔子', pinyin: 'tùzi', ja: 'ウサギ', hiragana: 'うさぎ' },
            { en: 'Wolf', ipa: '/wʊlf/', zh: '狼', pinyin: 'láng', ja: 'オオカミ', hiragana: 'おおかみ' },
            { en: 'Bear', ipa: '/bɛər/', zh: '熊', pinyin: 'xióng', ja: 'クマ', hiragana: 'くま' },
            { en: 'Fox', ipa: '/fɒks/', zh: '狐狸', pinyin: 'húlí', ja: 'キツネ', hiragana: 'きつね' },
            { en: 'Deer', ipa: '/dɪər/', zh: '鹿', pinyin: 'lù', ja: '鹿', hiragana: 'しか' },
            { en: 'Lion', ipa: '/ˈlaɪən/', zh: '獅子', pinyin: 'shīzi', ja: 'ライオン', hiragana: 'らいおん' },
            { en: 'Tiger', ipa: '/ˈtaɪɡər/', zh: '老虎', pinyin: 'lǎohǔ', ja: 'トラ', hiragana: 'とら' },
        ],
        [
            { en: 'Eagle', ipa: '/ˈiːɡl/', zh: '老鷹', pinyin: 'lǎoyīng', ja: 'ワシ', hiragana: 'わし' },
            { en: 'Penguin', ipa: '/ˈpɛnɡwɪn/', zh: '企鵝', pinyin: 'qǐé', ja: 'ペンギン', hiragana: 'ぺんぎん' },
            { en: 'Parrot', ipa: '/ˈpærət/', zh: '鸚鵡', pinyin: 'yīngwǔ', ja: 'オウム', hiragana: 'おうむ' },
            { en: 'Owl', ipa: '/aʊl/', zh: '貓頭鷹', pinyin: 'māotóuyīng', ja: 'フクロウ', hiragana: 'ふくろう' },
            { en: 'Flamingo', ipa: '/fləˈmɪŋɡoʊ/', zh: '紅鶴', pinyin: 'hónghè', ja: 'フラミンゴ', hiragana: 'ふらみんご' },
            { en: 'Peacock', ipa: '/ˈpiːkɒk/', zh: '孔雀', pinyin: 'kǒngquè', ja: '孔雀', hiragana: 'くじゃく' },
            { en: 'Swan', ipa: '/swɒn/', zh: '天鵝', pinyin: 'tiāné', ja: '白鳥', hiragana: 'はくちょう' },
            { en: 'Crow', ipa: '/kroʊ/', zh: '烏鴉', pinyin: 'wūyā', ja: 'カラス', hiragana: 'からす' },
            { en: 'Hawk', ipa: '/hɔːk/', zh: '鷹', pinyin: 'yīng', ja: 'タカ', hiragana: 'たか' },
            { en: 'Pelican', ipa: '/ˈpɛlɪkən/', zh: '鵜鶘', pinyin: 'tíhú', ja: 'ペリカン', hiragana: 'ぺりかん' },
        ],
        [
            { en: 'Shark', ipa: '/ʃɑːrk/', zh: '鯊魚', pinyin: 'shāyú', ja: 'サメ', hiragana: 'さめ' },
            { en: 'Octopus', ipa: '/ˈɒktəpəs/', zh: '章魚', pinyin: 'zhāngyú', ja: 'タコ', hiragana: 'たこ' },
            { en: 'Dolphin', ipa: '/ˈdɒlfɪn/', zh: '海豚', pinyin: 'hǎitún', ja: 'イルカ', hiragana: 'いるか' },
            { en: 'Whale', ipa: '/weɪl/', zh: '鯨魚', pinyin: 'jīngyú', ja: 'クジラ', hiragana: 'くじら' },
            { en: 'Crab', ipa: '/kræb/', zh: '螃蟹', pinyin: 'pángxiè', ja: 'カニ', hiragana: 'かに' },
            { en: 'Jellyfish', ipa: '/ˈdʒɛlɪfɪʃ/', zh: '水母', pinyin: 'shuǐmǔ', ja: 'クラゲ', hiragana: 'くらげ' },
            { en: 'Lobster', ipa: '/ˈlɒbstər/', zh: '龍蝦', pinyin: 'lóngxiā', ja: 'ロブスター', hiragana: 'ろぶすたー' },
            { en: 'Turtle', ipa: '/ˈtɜːrtl/', zh: '烏龜', pinyin: 'wūguī', ja: 'カメ', hiragana: 'かめ' },
            { en: 'Seahorse', ipa: '/ˈsiːhɔːrs/', zh: '海馬', pinyin: 'hǎimǎ', ja: 'タツノオトシゴ', hiragana: 'たつのおとしご' },
            { en: 'Clownfish', ipa: '/ˈklaʊnfɪʃ/', zh: '小丑魚', pinyin: 'xiǎochǒuyú', ja: 'クマノミ', hiragana: 'くまのみ' },
        ],
    ],
    food: [
        [
            { en: 'Pizza', ipa: '/ˈpiːtsə/', zh: '披薩', pinyin: 'pīsà', ja: 'ピザ', hiragana: 'ぴざ' },
            { en: 'Burger', ipa: '/ˈbɜːrɡər/', zh: '漢堡', pinyin: 'hànbǎo', ja: 'バーガー', hiragana: 'ばーがー' },
            { en: 'Sushi', ipa: '/ˈsuːʃi/', zh: '壽司', pinyin: 'shòusī', ja: '寿司', hiragana: 'すし' },
            { en: 'Tacos', ipa: '/ˈtɑːkoʊz/', zh: '墨西哥捲', pinyin: 'mòxīgējuǎn', ja: 'タコス', hiragana: 'たこす' },
            { en: 'Pasta', ipa: '/ˈpɑːstə/', zh: '義大利麵', pinyin: 'yìdàlìmiàn', ja: 'パスタ', hiragana: 'ぱすた' },
            { en: 'Ramen', ipa: '/ˈrɑːmɛn/', zh: '拉麵', pinyin: 'lāmiàn', ja: 'ラーメン', hiragana: 'らーめん' },
            { en: 'Steak', ipa: '/steɪk/', zh: '牛排', pinyin: 'niúpái', ja: 'ステーキ', hiragana: 'すてーき' },
            { en: 'Curry', ipa: '/ˈkɜːri/', zh: '咖哩', pinyin: 'gālǐ', ja: 'カレー', hiragana: 'かれー' },
            { en: 'Dumpling', ipa: '/ˈdʌmplɪŋ/', zh: '餃子', pinyin: 'jiǎozi', ja: '餃子', hiragana: 'ぎょうざ' },
            { en: 'Croissant', ipa: '/krwɑːˈsɒ̃/', zh: '可頌', pinyin: 'kěsòng', ja: 'クロワッサン', hiragana: 'くろわっさん' },
        ],
        [
            { en: 'Apple', ipa: '/ˈæpl/', zh: '蘋果', pinyin: 'píngguǒ', ja: 'リンゴ', hiragana: 'りんご' },
            { en: 'Mango', ipa: '/ˈmæŋɡoʊ/', zh: '芒果', pinyin: 'mángguǒ', ja: 'マンゴー', hiragana: 'まんごー' },
            { en: 'Grape', ipa: '/ɡreɪp/', zh: '葡萄', pinyin: 'pútáo', ja: 'ブドウ', hiragana: 'ぶどう' },
            { en: 'Watermelon', ipa: '/ˈwɔːtərmɛlən/', zh: '西瓜', pinyin: 'xīguā', ja: 'スイカ', hiragana: 'すいか' },
            { en: 'Strawberry', ipa: '/ˈstrɔːbəri/', zh: '草莓', pinyin: 'cǎoméi', ja: 'イチゴ', hiragana: 'いちご' },
            { en: 'Peach', ipa: '/piːtʃ/', zh: '桃子', pinyin: 'táozi', ja: '桃', hiragana: 'もも' },
            { en: 'Lemon', ipa: '/ˈlɛmən/', zh: '檸檬', pinyin: 'níngméng', ja: 'レモン', hiragana: 'れもん' },
            { en: 'Cherry', ipa: '/ˈtʃɛri/', zh: '櫻桃', pinyin: 'yīngtáo', ja: 'チェリー', hiragana: 'ちぇりー' },
            { en: 'Pineapple', ipa: '/ˈpaɪnæpl/', zh: '鳳梨', pinyin: 'fènglí', ja: 'パイナップル', hiragana: 'ぱいなっぷる' },
            { en: 'Coconut', ipa: '/ˈkoʊkənʌt/', zh: '椰子', pinyin: 'yēzi', ja: 'ココナッツ', hiragana: 'ここなっつ' },
        ],
        [
            { en: 'Cake', ipa: '/keɪk/', zh: '蛋糕', pinyin: 'dàngāo', ja: 'ケーキ', hiragana: 'けーき' },
            { en: 'Donut', ipa: '/ˈdoʊnʌt/', zh: '甜甜圈', pinyin: 'tiántiánquān', ja: 'ドーナツ', hiragana: 'どーなつ' },
            { en: 'Ice Cream', ipa: '/aɪs kriːm/', zh: '冰淇淋', pinyin: 'bīngqílín', ja: 'アイスクリーム', hiragana: 'あいすくりーむ' },
            { en: 'Waffle', ipa: '/ˈwɒfl/', zh: '鬆餅', pinyin: 'sōngbǐng', ja: 'ワッフル', hiragana: 'わっふる' },
            { en: 'Macaron', ipa: '/mækəˈrɒn/', zh: '馬卡龍', pinyin: 'mǎkǎlóng', ja: 'マカロン', hiragana: 'まかろん' },
            { en: 'Pudding', ipa: '/ˈpʊdɪŋ/', zh: '布丁', pinyin: 'bùdīng', ja: 'プリン', hiragana: 'ぷりん' },
            { en: 'Brownie', ipa: '/ˈbraʊni/', zh: '布朗尼', pinyin: 'bùlǎngní', ja: 'ブラウニー', hiragana: 'ぶらうにー' },
            { en: 'Mochi', ipa: '/ˈmoʊtʃi/', zh: '麻糬', pinyin: 'máshǔ', ja: '餅', hiragana: 'もち' },
            { en: 'Tiramisu', ipa: '/ˌtɪrəmɪˈsuː/', zh: '提拉米蘇', pinyin: 'tílāmǐsū', ja: 'ティラミス', hiragana: 'てぃらみす' },
            { en: 'Cheesecake', ipa: '/ˈtʃiːzkeɪk/', zh: '起司蛋糕', pinyin: 'qǐsīdàngāo', ja: 'チーズケーキ', hiragana: 'ちーずけーき' },
        ],
    ],
    verb: [
        [
            { en: 'Run', ipa: '/rʌn/', zh: '跑', pinyin: 'pǎo', ja: '走る', hiragana: 'はしる' },
            { en: 'Jump', ipa: '/dʒʌmp/', zh: '跳', pinyin: 'tiào', ja: '跳ぶ', hiragana: 'とぶ' },
            { en: 'Swim', ipa: '/swɪm/', zh: '游泳', pinyin: 'yóuyǒng', ja: '泳ぐ', hiragana: 'およぐ' },
            { en: 'Fly', ipa: '/flaɪ/', zh: '飛', pinyin: 'fēi', ja: '飛ぶ', hiragana: 'とぶ' },
            { en: 'Climb', ipa: '/klaɪm/', zh: '爬', pinyin: 'pá', ja: '登る', hiragana: 'のぼる' },
            { en: 'Dance', ipa: '/dæns/', zh: '跳舞', pinyin: 'tiàowǔ', ja: '踊る', hiragana: 'おどる' },
            { en: 'Sing', ipa: '/sɪŋ/', zh: '唱歌', pinyin: 'chànggē', ja: '歌う', hiragana: 'うたう' },
            { en: 'Crawl', ipa: '/krɔːl/', zh: '爬行', pinyin: 'páxíng', ja: '這う', hiragana: 'はう' },
            { en: 'Spin', ipa: '/spɪn/', zh: '旋轉', pinyin: 'xuánzhuǎn', ja: '回る', hiragana: 'まわる' },
            { en: 'Roll', ipa: '/roʊl/', zh: '滾動', pinyin: 'gǔndòng', ja: '転がる', hiragana: 'ころがる' },
        ],
        [
            { en: 'Laugh', ipa: '/læf/', zh: '笑', pinyin: 'xiào', ja: '笑う', hiragana: 'わらう' },
            { en: 'Cry', ipa: '/kraɪ/', zh: '哭', pinyin: 'kū', ja: '泣く', hiragana: 'なく' },
            { en: 'Scream', ipa: '/skriːm/', zh: '尖叫', pinyin: 'jiānjiào', ja: '叫ぶ', hiragana: 'さけぶ' },
            { en: 'Whisper', ipa: '/ˈwɪspər/', zh: '耳語', pinyin: 'ěryǔ', ja: 'ささやく', hiragana: 'ささやく' },
            { en: 'Argue', ipa: '/ˈɑːrɡjuː/', zh: '爭吵', pinyin: 'zhēngchǎo', ja: '言い争う', hiragana: 'いいあらそう' },
            { en: 'Hug', ipa: '/hʌɡ/', zh: '擁抱', pinyin: 'yōngbào', ja: '抱きしめる', hiragana: 'だきしめる' },
            { en: 'Kiss', ipa: '/kɪs/', zh: '親吻', pinyin: 'qīnwěn', ja: 'キスする', hiragana: 'きすする' },
            { en: 'Stare', ipa: '/stɛər/', zh: '凝視', pinyin: 'níngshì', ja: '見つめる', hiragana: 'みつめる' },
            { en: 'Blink', ipa: '/blɪŋk/', zh: '眨眼', pinyin: 'zhǎyǎn', ja: 'まばたく', hiragana: 'まばたく' },
            { en: 'Smile', ipa: '/smaɪl/', zh: '微笑', pinyin: 'wéixiào', ja: '微笑む', hiragana: 'ほほえむ' },
        ],
        [
            { en: 'Cook', ipa: '/kʊk/', zh: '烹飪', pinyin: 'pēngrèn', ja: '料理する', hiragana: 'りょうりする' },
            { en: 'Build', ipa: '/bɪld/', zh: '建造', pinyin: 'jiànzào', ja: '建てる', hiragana: 'たてる' },
            { en: 'Draw', ipa: '/drɔː/', zh: '畫畫', pinyin: 'huàhuà', ja: '描く', hiragana: 'えがく' },
            { en: 'Write', ipa: '/raɪt/', zh: '寫作', pinyin: 'xiězuò', ja: '書く', hiragana: 'かく' },
            { en: 'Read', ipa: '/riːd/', zh: '閱讀', pinyin: 'yuèdú', ja: '読む', hiragana: 'よむ' },
            { en: 'Teach', ipa: '/tiːtʃ/', zh: '教導', pinyin: 'jiàodǎo', ja: '教える', hiragana: 'おしえる' },
            { en: 'Steal', ipa: '/stiːl/', zh: '偷竊', pinyin: 'tōuqiè', ja: '盗む', hiragana: 'ぬすむ' },
            { en: 'Fix', ipa: '/fɪks/', zh: '修理', pinyin: 'xiūlǐ', ja: '直す', hiragana: 'なおす' },
            { en: 'Hunt', ipa: '/hʌnt/', zh: '狩獵', pinyin: 'shòuliè', ja: '狩る', hiragana: 'かる' },
            { en: 'Plant', ipa: '/plænt/', zh: '種植', pinyin: 'zhòngzhí', ja: '植える', hiragana: 'うえる' },
        ],
    ],
    adjective: [
        [
            { en: 'Happy', ipa: '/ˈhæpi/', zh: '快樂的', pinyin: 'kuàilède', ja: '嬉しい', hiragana: 'うれしい' },
            { en: 'Sad', ipa: '/sæd/', zh: '悲傷的', pinyin: 'bēishāngde', ja: '悲しい', hiragana: 'かなしい' },
            { en: 'Angry', ipa: '/ˈæŋɡri/', zh: '憤怒的', pinyin: 'fènnùde', ja: '怒った', hiragana: 'おこった' },
            { en: 'Scared', ipa: '/skɛərd/', zh: '害怕的', pinyin: 'hàipàde', ja: '怖い', hiragana: 'こわい' },
            { en: 'Bored', ipa: '/bɔːrd/', zh: '無聊的', pinyin: 'wúliáode', ja: '退屈な', hiragana: 'たいくつな' },
            { en: 'Excited', ipa: '/ɪkˈsaɪtɪd/', zh: '興奮的', pinyin: 'xīngfènde', ja: 'わくわくした', hiragana: 'わくわくした' },
            { en: 'Tired', ipa: '/ˈtaɪərd/', zh: '疲倦的', pinyin: 'píjuǎnde', ja: '疲れた', hiragana: 'つかれた' },
            { en: 'Nervous', ipa: '/ˈnɜːrvəs/', zh: '緊張的', pinyin: 'jǐnzhāngde', ja: '緊張した', hiragana: 'きんちょうした' },
            { en: 'Jealous', ipa: '/ˈdʒɛləs/', zh: '嫉妒的', pinyin: 'jídùde', ja: '嫉妬深い', hiragana: 'しっとぶかい' },
            { en: 'Proud', ipa: '/praʊd/', zh: '驕傲的', pinyin: 'jiāoàode', ja: '誇りに思う', hiragana: 'ほこりにおもう' },
        ],
        [
            { en: 'Tiny', ipa: '/ˈtaɪni/', zh: '微小的', pinyin: 'wēixiǎode', ja: '小さな', hiragana: 'ちいさな' },
            { en: 'Huge', ipa: '/hjuːdʒ/', zh: '巨大的', pinyin: 'jùdàde', ja: '巨大な', hiragana: 'きょだいな' },
            { en: 'Heavy', ipa: '/ˈhɛvi/', zh: '沉重的', pinyin: 'chénzhòngde', ja: '重い', hiragana: 'おもい' },
            { en: 'Light', ipa: '/laɪt/', zh: '輕盈的', pinyin: 'qīngyíngde', ja: '軽い', hiragana: 'かるい' },
            { en: 'Rough', ipa: '/rʌf/', zh: '粗糙的', pinyin: 'cūcāode', ja: 'ざらざらした', hiragana: 'ざらざらした' },
            { en: 'Smooth', ipa: '/smuːð/', zh: '光滑的', pinyin: 'guānghuáde', ja: 'なめらかな', hiragana: 'なめらかな' },
            { en: 'Sharp', ipa: '/ʃɑːrp/', zh: '鋒利的', pinyin: 'fēnglìde', ja: '鋭い', hiragana: 'するどい' },
            { en: 'Soft', ipa: '/sɒft/', zh: '柔軟的', pinyin: 'róuruǎnde', ja: '柔らかい', hiragana: 'やわらかい' },
            { en: 'Cold', ipa: '/koʊld/', zh: '寒冷的', pinyin: 'hánlěngde', ja: '冷たい', hiragana: 'つめたい' },
            { en: 'Burning', ipa: '/ˈbɜːrnɪŋ/', zh: '燃燒的', pinyin: 'ránshāode', ja: '燃える', hiragana: 'もえる' },
        ],
        [
            { en: 'Brave', ipa: '/breɪv/', zh: '勇敢的', pinyin: 'yǒnggǎnde', ja: '勇敢な', hiragana: 'ゆうかんな' },
            { en: 'Clever', ipa: '/ˈklɛvər/', zh: '聰明的', pinyin: 'cōngmíngde', ja: '賢い', hiragana: 'かしこい' },
            { en: 'Lazy', ipa: '/ˈleɪzi/', zh: '懶惰的', pinyin: 'lǎnduòde', ja: '怠惰な', hiragana: 'たいだな' },
            { en: 'Cruel', ipa: '/ˈkruːəl/', zh: '殘忍的', pinyin: 'cánrěnde', ja: '残酷な', hiragana: 'ざんこくな' },
            { en: 'Gentle', ipa: '/ˈdʒɛntl/', zh: '溫柔的', pinyin: 'wēnróude', ja: '優しい', hiragana: 'やさしい' },
            { en: 'Greedy', ipa: '/ˈɡriːdi/', zh: '貪婪的', pinyin: 'tānlände', ja: '欲張りな', hiragana: 'よくばりな' },
            { en: 'Honest', ipa: '/ˈɒnɪst/', zh: '誠實的', pinyin: 'chéngshíde', ja: '正直な', hiragana: 'しょうじきな' },
            { en: 'Reckless', ipa: '/ˈrɛklɪs/', zh: '魯莽的', pinyin: 'lǔmǎngde', ja: '無謀な', hiragana: 'むぼうな' },
            { en: 'Stubborn', ipa: '/ˈstʌbərn/', zh: '頑固的', pinyin: 'wángùde', ja: '頑固な', hiragana: 'がんこな' },
            { en: 'Sneaky', ipa: '/ˈsniːki/', zh: '狡猾的', pinyin: 'jiǎohuáde', ja: 'ずるい', hiragana: 'ずるい' },
        ],
    ],
    adverb: [
        [
            { en: 'Quickly', ipa: '/ˈkwɪkli/', zh: '迅速地', pinyin: 'xùnsùde', ja: '素早く', hiragana: 'すばやく' },
            { en: 'Slowly', ipa: '/ˈsloʊli/', zh: '緩慢地', pinyin: 'huǎnmànde', ja: 'ゆっくりと', hiragana: 'ゆっくりと' },
            { en: 'Quietly', ipa: '/ˈkwaɪətli/', zh: '安靜地', pinyin: 'ānjìngde', ja: '静かに', hiragana: 'しずかに' },
            { en: 'Loudly', ipa: '/ˈlaʊdli/', zh: '大聲地', pinyin: 'dàshēngde', ja: '大きな声で', hiragana: 'おおきなこえで' },
            { en: 'Carefully', ipa: '/ˈkɛərfəli/', zh: '小心地', pinyin: 'xiǎoxīnde', ja: '注意深く', hiragana: 'ちゅういぶかく' },
            { en: 'Wildly', ipa: '/ˈwaɪldli/', zh: '瘋狂地', pinyin: 'fēngkuángde', ja: '激しく', hiragana: 'はげしく' },
            { en: 'Gently', ipa: '/ˈdʒɛntli/', zh: '輕柔地', pinyin: 'qīngróude', ja: '優しく', hiragana: 'やさしく' },
            { en: 'Roughly', ipa: '/ˈrʌfli/', zh: '粗暴地', pinyin: 'cūbàode', ja: '乱暴に', hiragana: 'らんぼうに' },
            { en: 'Suddenly', ipa: '/ˈsʌdənli/', zh: '突然地', pinyin: 'tūránde', ja: '突然', hiragana: 'とつぜん' },
            { en: 'Lazily', ipa: '/ˈleɪzɪli/', zh: '懶洋洋地', pinyin: 'lǎnyángyángde', ja: 'だらだらと', hiragana: 'だらだらと' },
        ],
        [
            { en: 'Always', ipa: '/ˈɔːlweɪz/', zh: '總是', pinyin: 'zǒngshì', ja: 'いつも', hiragana: 'いつも' },
            { en: 'Never', ipa: '/ˈnɛvər/', zh: '從不', pinyin: 'cóngbù', ja: '決して〜ない', hiragana: 'けっして〜ない' },
            { en: 'Sometimes', ipa: '/ˈsʌmtaɪmz/', zh: '有時', pinyin: 'yǒushí', ja: '時々', hiragana: 'ときどき' },
            { en: 'Often', ipa: '/ˈɒfən/', zh: '經常', pinyin: 'jīngcháng', ja: 'よく', hiragana: 'よく' },
            { en: 'Rarely', ipa: '/ˈrɛərli/', zh: '很少', pinyin: 'hěnshǎo', ja: 'めったに〜ない', hiragana: 'めったに〜ない' },
            { en: 'Already', ipa: '/ɔːlˈrɛdi/', zh: '已經', pinyin: 'yǐjīng', ja: 'すでに', hiragana: 'すでに' },
            { en: 'Soon', ipa: '/suːn/', zh: '很快', pinyin: 'hěnkuài', ja: 'もうすぐ', hiragana: 'もうすぐ' },
            { en: 'Still', ipa: '/stɪl/', zh: '仍然', pinyin: 'réngrán', ja: 'まだ', hiragana: 'まだ' },
            { en: 'Forever', ipa: '/fərˈɛvər/', zh: '永遠', pinyin: 'yǒngyuǎn', ja: '永遠に', hiragana: 'えいえんに' },
            { en: 'Lately', ipa: '/ˈleɪtli/', zh: '最近', pinyin: 'zuìjìn', ja: '最近', hiragana: 'さいきん' },
        ],
        [
            { en: 'Everywhere', ipa: '/ˈɛvriwɛər/', zh: '到處', pinyin: 'dàochù', ja: 'どこでも', hiragana: 'どこでも' },
            { en: 'Nowhere', ipa: '/ˈnoʊwɛər/', zh: '無處', pinyin: 'wúchù', ja: 'どこにもない', hiragana: 'どこにもない' },
            { en: 'Nearby', ipa: '/ˈnɪərbaɪ/', zh: '附近', pinyin: 'fùjìn', ja: '近くに', hiragana: 'ちかくに' },
            { en: 'Far Away', ipa: '/fɑːr əˈweɪ/', zh: '遠處', pinyin: 'yuǎnchù', ja: '遠くに', hiragana: 'とおくに' },
            { en: 'Upstairs', ipa: '/ˌʌpˈstɛərz/', zh: '樓上', pinyin: 'lóushàng', ja: '上の階に', hiragana: 'うえのかいに' },
            { en: 'Outside', ipa: '/ˌaʊtˈsaɪd/', zh: '外面', pinyin: 'wàimiàn', ja: '外に', hiragana: 'そとに' },
            { en: 'Inside', ipa: '/ˌɪnˈsaɪd/', zh: '裡面', pinyin: 'lǐmiàn', ja: '中に', hiragana: 'なかに' },
            { en: 'Apart', ipa: '/əˈpɑːrt/', zh: '分開地', pinyin: 'fēnkāide', ja: '離れて', hiragana: 'はなれて' },
            { en: 'Together', ipa: '/təˈɡɛðər/', zh: '一起', pinyin: 'yìqǐ', ja: '一緒に', hiragana: 'いっしょに' },
            { en: 'Alone', ipa: '/əˈloʊn/', zh: '獨自地', pinyin: 'dúzìde', ja: '一人で', hiragana: 'ひとりで' },
        ],
    ],
};
